propertiesPluginEnvironmentNameProperty=platformVersion
# Platform environment is selected by platformVersion.
platformVersion=262
baseIDE=IC
ideToRun=

buildNumber=999999-SNAPSHOT

publishToken=token
publishChannel=dev

githubToken=token

showTestStatus=false
showStandardStreams=false
enableBuildSearchableOptions=false
compileNativeCode=false

org.gradle.jvmargs=-Xmx3g

# Enable Gradle Build Cache. It is also configured in settings.gradle.kts.
org.gradle.caching=false

systemProp.org.gradle.internal.repository.max.tentatives=10
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000

# Since kotlin 1.4, stdlib dependency is added by default by kotlin gradle plugin.
# But we don't need it because all necessary kotlin libraries are already bundled into IDE.
kotlin.stdlib.default.dependency=false
